name: Deployment
on:
  push:
    branches:
      - "**"
jobs:
  build-wasm:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - uses: mymindstorm/setup-emsdk@v11
      - name: Verify
        run: emcc -v
      - run: npm install
      - run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      # - run: npm run release "${{ github.event.release.tag_name }}"
      - run: npm run release "v0.1.11"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
      - run: |
          git push --follow-tags origin HEAD:main
