name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm ci
      - run: npm run build --if-present
      - name: Run tree-sitter playground
        run: | 
          npm run playground &
          while ! nc -z localhost 8000; do
            sleep 3
          done

      - name: Download aseets
        run: wget -T 10 -P public -nH -r https://127.0.0.1:8000/{,tree-sitter.wasm,tree-sitter-parser.wasm}

      - name: Modify assets
        run: sed -i 's,LANGUAGE_BASE_URL = "";,LANGUAGE_BASE_URL = new URL(window.location.href).pathname;,' public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
